name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    container:
      image: ros:noetic-ros-core  # 使用预装了 ROS Core 的官方镜像

    steps:
      - name: Install Act dependencies
        if: ${{ env.ACT }}
        run: |
          apt-get update && apt-get install sudo -y

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install curl build-essential git -y
          sudo apt-get install python3-rosdep libyaml-cpp-dev libpcap-dev dh-make -y
          rm /bin/sh && ln -s /bin/bash /bin/sh

      # 检出代码
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive  # 递归更新所有子模块


      # 安装 ROS 依赖
      - name: Install ROS dependencies
        run: |
          source /opt/ros/noetic/setup.bash
          rosdep init || true
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      # 构建项目
      - name: Build the project
        run: |
          source /opt/ros/noetic/setup.bash
          bash create_debian.sh
          mkdir output
          mv ../*.deb /

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: my-artifact
          path: /*.deb